# Generated by Django 5.1.7 on 2025-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tootekood', models.IntegerField()),
                ('nimi', models.CharField(max_length=150)),
                ('kirjeldus', models.TextField()),
            ],
        ),
    ]
