# Generated by Django 5.1.7 on 2025-03-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varvitabel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projektid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt', models.CharField(max_length=30)),
                ('staatus', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=150)),
            ],
        ),
    ]
