# Generated by Django 5.1.7 on 2025-03-29 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varvitabel', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='komplekteeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kogus', models.IntegerField()),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='komplekteeri', to='varvitabel.task')),
                ('toode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='varvitabel.toode')),
            ],
        ),
    ]
