# Generated by Django 5.1.7 on 2025-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varvitabel', '0005_komplekteeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='komplekteeri',
            name='komplekteeritudkogus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='komplekteeri',
            name='kogus',
            field=models.IntegerField(null=True),
        ),
    ]
