# Generated by Django 5.1.7 on 2025-04-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varvitabel', '0006_komplekteeri_komplekteeritudkogus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toode',
            name='tootekood',
            field=models.IntegerField(unique=True),
        ),
    ]
