# Generated by Django 5.1.7 on 2025-04-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varvitabel', '0008_projektivaadeform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projektivaadeform',
            new_name='projektivaade',
        ),
    ]
